# Generated by Django 3.1.7 on 2021-02-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='phonenumber',
            field=models.IntegerField(),
        ),
    ]
