# Generated by Django 3.1.7 on 2021-02-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210222_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumbercsv',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
